### ISSUE TITLE
buc を簡潔に書けるようにする

### ISSUE THREAD

**Issue by tango238** [tango238/rdra#25]
buc を書くときに書く量が多い。
BUCの一覧はさっと書き出したいので簡潔に書けるようにする。

## 変更前
```
    buc:
      - name: aaa
        activity:
          - name: bbb
            used_by:
              - ccc
```

## 変更後（変更前の書き方もできるようにしておく）
```
    buc:
      - aaa1
      - aaa2
      - aaa3
```
