### ISSUE TITLE
buc に used_by/usecase をぶら下げられるようにする

### ISSUE THREAD

**Issue by tango238** [tango238/rdra#3]
`buc` か `activity` のどちらかに `used_by/usecase` を設定できる。

```
- name: 会員の確認
   used_by:
     - 図書館員
   usecase:
     - 会員カードの発行（再）する
     - 会員を照会する
```

`usecase` を設定したのがシステム境界になる。（＝画面）
